### ISSUE TITLE
Pong: To-Do 리스트

### ISSUE THREAD

**Issue by devleomk1** [42Blank/ft_transcendence#125]
- [ ] #121  
- [ ] 게임 결과 페이지
- [ ] 게임 준비 페이지 (대기방)
- [ ] 관전자 입장 기능
- [ ] #88 
- [ ] 게임 최.적.화.
- [ ] (Opt) 서브 y좌표 랜덤화
- [ ] (Opt) #56 

우선순위 순으로 정렬되어 있습니다.

**Comment by devleomk1** [comment]
![image](https://user-images.githubusercontent.com/73428595/220112604-6d3603a6-f98e-4a37-8d83-ecf8c85172a6.png)
할 거 너무 많아
